// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: broker/address.proto

package org.doodle.broker;

/**
 * Protobuf type {@code doodle.broker.BrokerAddress}
 */
public final class BrokerAddress extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:doodle.broker.BrokerAddress)
    BrokerAddressOrBuilder {
private static final long serialVersionUID = 0L;
  // Use BrokerAddress.newBuilder() to construct.
  private BrokerAddress(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private BrokerAddress() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new BrokerAddress();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private BrokerAddress(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            org.doodle.broker.BrokerRouteId.Builder subBuilder = null;
            if (routeId_ != null) {
              subBuilder = routeId_.toBuilder();
            }
            routeId_ = input.readMessage(org.doodle.broker.BrokerRouteId.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(routeId_);
              routeId_ = subBuilder.buildPartial();
            }

            break;
          }
          case 16: {

            flag_ = input.readInt32();
            break;
          }
          case 26: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              tags_ = com.google.protobuf.MapField.newMapField(
                  TagsDefaultEntryHolder.defaultEntry);
              mutable_bitField0_ |= 0x00000001;
            }
            com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
            tags__ = input.readMessage(
                TagsDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
            tags_.getMutableMap().put(
                tags__.getKey(), tags__.getValue());
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (com.google.protobuf.UninitializedMessageException e) {
      throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.doodle.broker.BrokerAddressProto.internal_static_doodle_broker_BrokerAddress_descriptor;
  }

  @SuppressWarnings({"rawtypes"})
  @java.lang.Override
  protected com.google.protobuf.MapField internalGetMapField(
      int number) {
    switch (number) {
      case 3:
        return internalGetTags();
      default:
        throw new RuntimeException(
            "Invalid map field number: " + number);
    }
  }
  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.doodle.broker.BrokerAddressProto.internal_static_doodle_broker_BrokerAddress_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.doodle.broker.BrokerAddress.class, org.doodle.broker.BrokerAddress.Builder.class);
  }

  public static final int ROUTE_ID_FIELD_NUMBER = 1;
  private org.doodle.broker.BrokerRouteId routeId_;
  /**
   * <code>.doodle.broker.BrokerRouteId route_id = 1;</code>
   * @return Whether the routeId field is set.
   */
  @java.lang.Override
  public boolean hasRouteId() {
    return routeId_ != null;
  }
  /**
   * <code>.doodle.broker.BrokerRouteId route_id = 1;</code>
   * @return The routeId.
   */
  @java.lang.Override
  public org.doodle.broker.BrokerRouteId getRouteId() {
    return routeId_ == null ? org.doodle.broker.BrokerRouteId.getDefaultInstance() : routeId_;
  }
  /**
   * <code>.doodle.broker.BrokerRouteId route_id = 1;</code>
   */
  @java.lang.Override
  public org.doodle.broker.BrokerRouteIdOrBuilder getRouteIdOrBuilder() {
    return getRouteId();
  }

  public static final int FLAG_FIELD_NUMBER = 2;
  private int flag_;
  /**
   * <code>int32 flag = 2;</code>
   * @return The flag.
   */
  @java.lang.Override
  public int getFlag() {
    return flag_;
  }

  public static final int TAGS_FIELD_NUMBER = 3;
  private static final class TagsDefaultEntryHolder {
    static final com.google.protobuf.MapEntry<
        java.lang.String, java.lang.String> defaultEntry =
            com.google.protobuf.MapEntry
            .<java.lang.String, java.lang.String>newDefaultInstance(
                org.doodle.broker.BrokerAddressProto.internal_static_doodle_broker_BrokerAddress_TagsEntry_descriptor, 
                com.google.protobuf.WireFormat.FieldType.STRING,
                "",
                com.google.protobuf.WireFormat.FieldType.STRING,
                "");
  }
  private com.google.protobuf.MapField<
      java.lang.String, java.lang.String> tags_;
  private com.google.protobuf.MapField<java.lang.String, java.lang.String>
  internalGetTags() {
    if (tags_ == null) {
      return com.google.protobuf.MapField.emptyMapField(
          TagsDefaultEntryHolder.defaultEntry);
    }
    return tags_;
  }

  public int getTagsCount() {
    return internalGetTags().getMap().size();
  }
  /**
   * <code>map&lt;string, string&gt; tags = 3;</code>
   */

  @java.lang.Override
  public boolean containsTags(
      java.lang.String key) {
    if (key == null) { throw new NullPointerException("map key"); }
    return internalGetTags().getMap().containsKey(key);
  }
  /**
   * Use {@link #getTagsMap()} instead.
   */
  @java.lang.Override
  @java.lang.Deprecated
  public java.util.Map<java.lang.String, java.lang.String> getTags() {
    return getTagsMap();
  }
  /**
   * <code>map&lt;string, string&gt; tags = 3;</code>
   */
  @java.lang.Override

  public java.util.Map<java.lang.String, java.lang.String> getTagsMap() {
    return internalGetTags().getMap();
  }
  /**
   * <code>map&lt;string, string&gt; tags = 3;</code>
   */
  @java.lang.Override

  public java.lang.String getTagsOrDefault(
      java.lang.String key,
      java.lang.String defaultValue) {
    if (key == null) { throw new NullPointerException("map key"); }
    java.util.Map<java.lang.String, java.lang.String> map =
        internalGetTags().getMap();
    return map.containsKey(key) ? map.get(key) : defaultValue;
  }
  /**
   * <code>map&lt;string, string&gt; tags = 3;</code>
   */
  @java.lang.Override

  public java.lang.String getTagsOrThrow(
      java.lang.String key) {
    if (key == null) { throw new NullPointerException("map key"); }
    java.util.Map<java.lang.String, java.lang.String> map =
        internalGetTags().getMap();
    if (!map.containsKey(key)) {
      throw new java.lang.IllegalArgumentException();
    }
    return map.get(key);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (routeId_ != null) {
      output.writeMessage(1, getRouteId());
    }
    if (flag_ != 0) {
      output.writeInt32(2, flag_);
    }
    com.google.protobuf.GeneratedMessageV3
      .serializeStringMapTo(
        output,
        internalGetTags(),
        TagsDefaultEntryHolder.defaultEntry,
        3);
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (routeId_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getRouteId());
    }
    if (flag_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, flag_);
    }
    for (java.util.Map.Entry<java.lang.String, java.lang.String> entry
         : internalGetTags().getMap().entrySet()) {
      com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
      tags__ = TagsDefaultEntryHolder.defaultEntry.newBuilderForType()
          .setKey(entry.getKey())
          .setValue(entry.getValue())
          .build();
      size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, tags__);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.doodle.broker.BrokerAddress)) {
      return super.equals(obj);
    }
    org.doodle.broker.BrokerAddress other = (org.doodle.broker.BrokerAddress) obj;

    if (hasRouteId() != other.hasRouteId()) return false;
    if (hasRouteId()) {
      if (!getRouteId()
          .equals(other.getRouteId())) return false;
    }
    if (getFlag()
        != other.getFlag()) return false;
    if (!internalGetTags().equals(
        other.internalGetTags())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasRouteId()) {
      hash = (37 * hash) + ROUTE_ID_FIELD_NUMBER;
      hash = (53 * hash) + getRouteId().hashCode();
    }
    hash = (37 * hash) + FLAG_FIELD_NUMBER;
    hash = (53 * hash) + getFlag();
    if (!internalGetTags().getMap().isEmpty()) {
      hash = (37 * hash) + TAGS_FIELD_NUMBER;
      hash = (53 * hash) + internalGetTags().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.doodle.broker.BrokerAddress parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.doodle.broker.BrokerAddress parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.doodle.broker.BrokerAddress parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.doodle.broker.BrokerAddress parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.doodle.broker.BrokerAddress parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.doodle.broker.BrokerAddress parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.doodle.broker.BrokerAddress parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.doodle.broker.BrokerAddress parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.doodle.broker.BrokerAddress parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static org.doodle.broker.BrokerAddress parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.doodle.broker.BrokerAddress parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.doodle.broker.BrokerAddress parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.doodle.broker.BrokerAddress prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code doodle.broker.BrokerAddress}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:doodle.broker.BrokerAddress)
      org.doodle.broker.BrokerAddressOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.doodle.broker.BrokerAddressProto.internal_static_doodle_broker_BrokerAddress_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 3:
          return internalGetTags();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMutableMapField(
        int number) {
      switch (number) {
        case 3:
          return internalGetMutableTags();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.doodle.broker.BrokerAddressProto.internal_static_doodle_broker_BrokerAddress_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.doodle.broker.BrokerAddress.class, org.doodle.broker.BrokerAddress.Builder.class);
    }

    // Construct using org.doodle.broker.BrokerAddress.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (routeIdBuilder_ == null) {
        routeId_ = null;
      } else {
        routeId_ = null;
        routeIdBuilder_ = null;
      }
      flag_ = 0;

      internalGetMutableTags().clear();
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.doodle.broker.BrokerAddressProto.internal_static_doodle_broker_BrokerAddress_descriptor;
    }

    @java.lang.Override
    public org.doodle.broker.BrokerAddress getDefaultInstanceForType() {
      return org.doodle.broker.BrokerAddress.getDefaultInstance();
    }

    @java.lang.Override
    public org.doodle.broker.BrokerAddress build() {
      org.doodle.broker.BrokerAddress result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public org.doodle.broker.BrokerAddress buildPartial() {
      org.doodle.broker.BrokerAddress result = new org.doodle.broker.BrokerAddress(this);
      int from_bitField0_ = bitField0_;
      if (routeIdBuilder_ == null) {
        result.routeId_ = routeId_;
      } else {
        result.routeId_ = routeIdBuilder_.build();
      }
      result.flag_ = flag_;
      result.tags_ = internalGetTags();
      result.tags_.makeImmutable();
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.doodle.broker.BrokerAddress) {
        return mergeFrom((org.doodle.broker.BrokerAddress)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.doodle.broker.BrokerAddress other) {
      if (other == org.doodle.broker.BrokerAddress.getDefaultInstance()) return this;
      if (other.hasRouteId()) {
        mergeRouteId(other.getRouteId());
      }
      if (other.getFlag() != 0) {
        setFlag(other.getFlag());
      }
      internalGetMutableTags().mergeFrom(
          other.internalGetTags());
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      org.doodle.broker.BrokerAddress parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (org.doodle.broker.BrokerAddress) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private org.doodle.broker.BrokerRouteId routeId_;
    private com.google.protobuf.SingleFieldBuilderV3<
        org.doodle.broker.BrokerRouteId, org.doodle.broker.BrokerRouteId.Builder, org.doodle.broker.BrokerRouteIdOrBuilder> routeIdBuilder_;
    /**
     * <code>.doodle.broker.BrokerRouteId route_id = 1;</code>
     * @return Whether the routeId field is set.
     */
    public boolean hasRouteId() {
      return routeIdBuilder_ != null || routeId_ != null;
    }
    /**
     * <code>.doodle.broker.BrokerRouteId route_id = 1;</code>
     * @return The routeId.
     */
    public org.doodle.broker.BrokerRouteId getRouteId() {
      if (routeIdBuilder_ == null) {
        return routeId_ == null ? org.doodle.broker.BrokerRouteId.getDefaultInstance() : routeId_;
      } else {
        return routeIdBuilder_.getMessage();
      }
    }
    /**
     * <code>.doodle.broker.BrokerRouteId route_id = 1;</code>
     */
    public Builder setRouteId(org.doodle.broker.BrokerRouteId value) {
      if (routeIdBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        routeId_ = value;
        onChanged();
      } else {
        routeIdBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.doodle.broker.BrokerRouteId route_id = 1;</code>
     */
    public Builder setRouteId(
        org.doodle.broker.BrokerRouteId.Builder builderForValue) {
      if (routeIdBuilder_ == null) {
        routeId_ = builderForValue.build();
        onChanged();
      } else {
        routeIdBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.doodle.broker.BrokerRouteId route_id = 1;</code>
     */
    public Builder mergeRouteId(org.doodle.broker.BrokerRouteId value) {
      if (routeIdBuilder_ == null) {
        if (routeId_ != null) {
          routeId_ =
            org.doodle.broker.BrokerRouteId.newBuilder(routeId_).mergeFrom(value).buildPartial();
        } else {
          routeId_ = value;
        }
        onChanged();
      } else {
        routeIdBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.doodle.broker.BrokerRouteId route_id = 1;</code>
     */
    public Builder clearRouteId() {
      if (routeIdBuilder_ == null) {
        routeId_ = null;
        onChanged();
      } else {
        routeId_ = null;
        routeIdBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.doodle.broker.BrokerRouteId route_id = 1;</code>
     */
    public org.doodle.broker.BrokerRouteId.Builder getRouteIdBuilder() {
      
      onChanged();
      return getRouteIdFieldBuilder().getBuilder();
    }
    /**
     * <code>.doodle.broker.BrokerRouteId route_id = 1;</code>
     */
    public org.doodle.broker.BrokerRouteIdOrBuilder getRouteIdOrBuilder() {
      if (routeIdBuilder_ != null) {
        return routeIdBuilder_.getMessageOrBuilder();
      } else {
        return routeId_ == null ?
            org.doodle.broker.BrokerRouteId.getDefaultInstance() : routeId_;
      }
    }
    /**
     * <code>.doodle.broker.BrokerRouteId route_id = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        org.doodle.broker.BrokerRouteId, org.doodle.broker.BrokerRouteId.Builder, org.doodle.broker.BrokerRouteIdOrBuilder> 
        getRouteIdFieldBuilder() {
      if (routeIdBuilder_ == null) {
        routeIdBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            org.doodle.broker.BrokerRouteId, org.doodle.broker.BrokerRouteId.Builder, org.doodle.broker.BrokerRouteIdOrBuilder>(
                getRouteId(),
                getParentForChildren(),
                isClean());
        routeId_ = null;
      }
      return routeIdBuilder_;
    }

    private int flag_ ;
    /**
     * <code>int32 flag = 2;</code>
     * @return The flag.
     */
    @java.lang.Override
    public int getFlag() {
      return flag_;
    }
    /**
     * <code>int32 flag = 2;</code>
     * @param value The flag to set.
     * @return This builder for chaining.
     */
    public Builder setFlag(int value) {
      
      flag_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 flag = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearFlag() {
      
      flag_ = 0;
      onChanged();
      return this;
    }

    private com.google.protobuf.MapField<
        java.lang.String, java.lang.String> tags_;
    private com.google.protobuf.MapField<java.lang.String, java.lang.String>
    internalGetTags() {
      if (tags_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            TagsDefaultEntryHolder.defaultEntry);
      }
      return tags_;
    }
    private com.google.protobuf.MapField<java.lang.String, java.lang.String>
    internalGetMutableTags() {
      onChanged();;
      if (tags_ == null) {
        tags_ = com.google.protobuf.MapField.newMapField(
            TagsDefaultEntryHolder.defaultEntry);
      }
      if (!tags_.isMutable()) {
        tags_ = tags_.copy();
      }
      return tags_;
    }

    public int getTagsCount() {
      return internalGetTags().getMap().size();
    }
    /**
     * <code>map&lt;string, string&gt; tags = 3;</code>
     */

    @java.lang.Override
    public boolean containsTags(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      return internalGetTags().getMap().containsKey(key);
    }
    /**
     * Use {@link #getTagsMap()} instead.
     */
    @java.lang.Override
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.String> getTags() {
      return getTagsMap();
    }
    /**
     * <code>map&lt;string, string&gt; tags = 3;</code>
     */
    @java.lang.Override

    public java.util.Map<java.lang.String, java.lang.String> getTagsMap() {
      return internalGetTags().getMap();
    }
    /**
     * <code>map&lt;string, string&gt; tags = 3;</code>
     */
    @java.lang.Override

    public java.lang.String getTagsOrDefault(
        java.lang.String key,
        java.lang.String defaultValue) {
      if (key == null) { throw new NullPointerException("map key"); }
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetTags().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;string, string&gt; tags = 3;</code>
     */
    @java.lang.Override

    public java.lang.String getTagsOrThrow(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetTags().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }

    public Builder clearTags() {
      internalGetMutableTags().getMutableMap()
          .clear();
      return this;
    }
    /**
     * <code>map&lt;string, string&gt; tags = 3;</code>
     */

    public Builder removeTags(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      internalGetMutableTags().getMutableMap()
          .remove(key);
      return this;
    }
    /**
     * Use alternate mutation accessors instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.String>
    getMutableTags() {
      return internalGetMutableTags().getMutableMap();
    }
    /**
     * <code>map&lt;string, string&gt; tags = 3;</code>
     */
    public Builder putTags(
        java.lang.String key,
        java.lang.String value) {
      if (key == null) { throw new NullPointerException("map key"); }
      if (value == null) {
  throw new NullPointerException("map value");
}

      internalGetMutableTags().getMutableMap()
          .put(key, value);
      return this;
    }
    /**
     * <code>map&lt;string, string&gt; tags = 3;</code>
     */

    public Builder putAllTags(
        java.util.Map<java.lang.String, java.lang.String> values) {
      internalGetMutableTags().getMutableMap()
          .putAll(values);
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:doodle.broker.BrokerAddress)
  }

  // @@protoc_insertion_point(class_scope:doodle.broker.BrokerAddress)
  private static final org.doodle.broker.BrokerAddress DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.doodle.broker.BrokerAddress();
  }

  public static org.doodle.broker.BrokerAddress getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<BrokerAddress>
      PARSER = new com.google.protobuf.AbstractParser<BrokerAddress>() {
    @java.lang.Override
    public BrokerAddress parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new BrokerAddress(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<BrokerAddress> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<BrokerAddress> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public org.doodle.broker.BrokerAddress getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

