// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: broker/frame.proto

package org.doodle.broker;

public interface BrokerFrameOrBuilder extends
    // @@protoc_insertion_point(interface_extends:doodle.broker.BrokerFrame)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.doodle.broker.BrokerAddress address = 1;</code>
   * @return Whether the address field is set.
   */
  boolean hasAddress();
  /**
   * <code>.doodle.broker.BrokerAddress address = 1;</code>
   * @return The address.
   */
  org.doodle.broker.BrokerAddress getAddress();
  /**
   * <code>.doodle.broker.BrokerAddress address = 1;</code>
   */
  org.doodle.broker.BrokerAddressOrBuilder getAddressOrBuilder();

  /**
   * <code>.doodle.broker.BrokerRouteSetup route_setup = 2;</code>
   * @return Whether the routeSetup field is set.
   */
  boolean hasRouteSetup();
  /**
   * <code>.doodle.broker.BrokerRouteSetup route_setup = 2;</code>
   * @return The routeSetup.
   */
  org.doodle.broker.BrokerRouteSetup getRouteSetup();
  /**
   * <code>.doodle.broker.BrokerRouteSetup route_setup = 2;</code>
   */
  org.doodle.broker.BrokerRouteSetupOrBuilder getRouteSetupOrBuilder();

  /**
   * <code>.doodle.broker.BrokerRouteJoin route_join = 3;</code>
   * @return Whether the routeJoin field is set.
   */
  boolean hasRouteJoin();
  /**
   * <code>.doodle.broker.BrokerRouteJoin route_join = 3;</code>
   * @return The routeJoin.
   */
  org.doodle.broker.BrokerRouteJoin getRouteJoin();
  /**
   * <code>.doodle.broker.BrokerRouteJoin route_join = 3;</code>
   */
  org.doodle.broker.BrokerRouteJoinOrBuilder getRouteJoinOrBuilder();

  /**
   * <code>.doodle.broker.BrokerInfo broker_info = 4;</code>
   * @return Whether the brokerInfo field is set.
   */
  boolean hasBrokerInfo();
  /**
   * <code>.doodle.broker.BrokerInfo broker_info = 4;</code>
   * @return The brokerInfo.
   */
  org.doodle.broker.BrokerInfo getBrokerInfo();
  /**
   * <code>.doodle.broker.BrokerInfo broker_info = 4;</code>
   */
  org.doodle.broker.BrokerInfoOrBuilder getBrokerInfoOrBuilder();

  public org.doodle.broker.BrokerFrame.FrameCase getFrameCase();
}
