// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: broker/route_setup.proto

package org.doodle.broker;

public final class BrokerRouteSetupProto {
  private BrokerRouteSetupProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_doodle_broker_BrokerRouteSetup_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_doodle_broker_BrokerRouteSetup_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_doodle_broker_BrokerRouteSetup_TagsEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_doodle_broker_BrokerRouteSetup_TagsEntry_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\030broker/route_setup.proto\022\rdoodle.broke" +
      "r\032\025broker/route_id.proto\"\250\001\n\020BrokerRoute" +
      "Setup\022.\n\010route_id\030\001 \001(\0132\034.doodle.broker." +
      "BrokerRouteId\0227\n\004tags\030\002 \003(\0132).doodle.bro" +
      "ker.BrokerRouteSetup.TagsEntry\032+\n\tTagsEn" +
      "try\022\013\n\003key\030\001 \001(\t\022\r\n\005value\030\002 \001(\t:\0028\001B,\n\021o" +
      "rg.doodle.brokerB\025BrokerRouteSetupProtoP" +
      "\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          org.doodle.broker.BrokerRouteIdProto.getDescriptor(),
        });
    internal_static_doodle_broker_BrokerRouteSetup_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_doodle_broker_BrokerRouteSetup_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_doodle_broker_BrokerRouteSetup_descriptor,
        new java.lang.String[] { "RouteId", "Tags", });
    internal_static_doodle_broker_BrokerRouteSetup_TagsEntry_descriptor =
      internal_static_doodle_broker_BrokerRouteSetup_descriptor.getNestedTypes().get(0);
    internal_static_doodle_broker_BrokerRouteSetup_TagsEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_doodle_broker_BrokerRouteSetup_TagsEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    org.doodle.broker.BrokerRouteIdProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
