// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: broker/route_id.proto

package org.doodle.broker;

/**
 * Protobuf type {@code doodle.broker.BrokerRouteId}
 */
public final class BrokerRouteId extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:doodle.broker.BrokerRouteId)
    BrokerRouteIdOrBuilder {
private static final long serialVersionUID = 0L;
  // Use BrokerRouteId.newBuilder() to construct.
  private BrokerRouteId(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private BrokerRouteId() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new BrokerRouteId();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private BrokerRouteId(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            msb_ = input.readInt64();
            break;
          }
          case 16: {

            lsb_ = input.readInt64();
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (com.google.protobuf.UninitializedMessageException e) {
      throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.doodle.broker.BrokerRouteIdProto.internal_static_doodle_broker_BrokerRouteId_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.doodle.broker.BrokerRouteIdProto.internal_static_doodle_broker_BrokerRouteId_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.doodle.broker.BrokerRouteId.class, org.doodle.broker.BrokerRouteId.Builder.class);
  }

  public static final int MSB_FIELD_NUMBER = 1;
  private long msb_;
  /**
   * <code>int64 msb = 1;</code>
   * @return The msb.
   */
  @java.lang.Override
  public long getMsb() {
    return msb_;
  }

  public static final int LSB_FIELD_NUMBER = 2;
  private long lsb_;
  /**
   * <code>int64 lsb = 2;</code>
   * @return The lsb.
   */
  @java.lang.Override
  public long getLsb() {
    return lsb_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (msb_ != 0L) {
      output.writeInt64(1, msb_);
    }
    if (lsb_ != 0L) {
      output.writeInt64(2, lsb_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (msb_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(1, msb_);
    }
    if (lsb_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(2, lsb_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.doodle.broker.BrokerRouteId)) {
      return super.equals(obj);
    }
    org.doodle.broker.BrokerRouteId other = (org.doodle.broker.BrokerRouteId) obj;

    if (getMsb()
        != other.getMsb()) return false;
    if (getLsb()
        != other.getLsb()) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + MSB_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getMsb());
    hash = (37 * hash) + LSB_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getLsb());
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.doodle.broker.BrokerRouteId parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.doodle.broker.BrokerRouteId parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.doodle.broker.BrokerRouteId parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.doodle.broker.BrokerRouteId parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.doodle.broker.BrokerRouteId parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.doodle.broker.BrokerRouteId parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.doodle.broker.BrokerRouteId parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.doodle.broker.BrokerRouteId parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.doodle.broker.BrokerRouteId parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static org.doodle.broker.BrokerRouteId parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.doodle.broker.BrokerRouteId parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.doodle.broker.BrokerRouteId parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.doodle.broker.BrokerRouteId prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code doodle.broker.BrokerRouteId}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:doodle.broker.BrokerRouteId)
      org.doodle.broker.BrokerRouteIdOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.doodle.broker.BrokerRouteIdProto.internal_static_doodle_broker_BrokerRouteId_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.doodle.broker.BrokerRouteIdProto.internal_static_doodle_broker_BrokerRouteId_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.doodle.broker.BrokerRouteId.class, org.doodle.broker.BrokerRouteId.Builder.class);
    }

    // Construct using org.doodle.broker.BrokerRouteId.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      msb_ = 0L;

      lsb_ = 0L;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.doodle.broker.BrokerRouteIdProto.internal_static_doodle_broker_BrokerRouteId_descriptor;
    }

    @java.lang.Override
    public org.doodle.broker.BrokerRouteId getDefaultInstanceForType() {
      return org.doodle.broker.BrokerRouteId.getDefaultInstance();
    }

    @java.lang.Override
    public org.doodle.broker.BrokerRouteId build() {
      org.doodle.broker.BrokerRouteId result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public org.doodle.broker.BrokerRouteId buildPartial() {
      org.doodle.broker.BrokerRouteId result = new org.doodle.broker.BrokerRouteId(this);
      result.msb_ = msb_;
      result.lsb_ = lsb_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.doodle.broker.BrokerRouteId) {
        return mergeFrom((org.doodle.broker.BrokerRouteId)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.doodle.broker.BrokerRouteId other) {
      if (other == org.doodle.broker.BrokerRouteId.getDefaultInstance()) return this;
      if (other.getMsb() != 0L) {
        setMsb(other.getMsb());
      }
      if (other.getLsb() != 0L) {
        setLsb(other.getLsb());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      org.doodle.broker.BrokerRouteId parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (org.doodle.broker.BrokerRouteId) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private long msb_ ;
    /**
     * <code>int64 msb = 1;</code>
     * @return The msb.
     */
    @java.lang.Override
    public long getMsb() {
      return msb_;
    }
    /**
     * <code>int64 msb = 1;</code>
     * @param value The msb to set.
     * @return This builder for chaining.
     */
    public Builder setMsb(long value) {
      
      msb_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 msb = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearMsb() {
      
      msb_ = 0L;
      onChanged();
      return this;
    }

    private long lsb_ ;
    /**
     * <code>int64 lsb = 2;</code>
     * @return The lsb.
     */
    @java.lang.Override
    public long getLsb() {
      return lsb_;
    }
    /**
     * <code>int64 lsb = 2;</code>
     * @param value The lsb to set.
     * @return This builder for chaining.
     */
    public Builder setLsb(long value) {
      
      lsb_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 lsb = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearLsb() {
      
      lsb_ = 0L;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:doodle.broker.BrokerRouteId)
  }

  // @@protoc_insertion_point(class_scope:doodle.broker.BrokerRouteId)
  private static final org.doodle.broker.BrokerRouteId DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.doodle.broker.BrokerRouteId();
  }

  public static org.doodle.broker.BrokerRouteId getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<BrokerRouteId>
      PARSER = new com.google.protobuf.AbstractParser<BrokerRouteId>() {
    @java.lang.Override
    public BrokerRouteId parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new BrokerRouteId(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<BrokerRouteId> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<BrokerRouteId> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public org.doodle.broker.BrokerRouteId getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

