// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: broker/broker_info.proto

package org.doodle.broker;

public interface BrokerInfoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:doodle.broker.BrokerInfo)
    com.google.protobuf.MessageOrBuilder {
}
