// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: broker/route_id.proto

package org.doodle.broker;

public interface BrokerRouteIdOrBuilder extends
    // @@protoc_insertion_point(interface_extends:doodle.broker.BrokerRouteId)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 msb = 1;</code>
   * @return The msb.
   */
  long getMsb();

  /**
   * <code>int64 lsb = 2;</code>
   * @return The lsb.
   */
  long getLsb();
}
