// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: broker/frame.proto

package org.doodle.broker;

/**
 * Protobuf type {@code doodle.broker.BrokerFrame}
 */
public final class BrokerFrame extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:doodle.broker.BrokerFrame)
    BrokerFrameOrBuilder {
private static final long serialVersionUID = 0L;
  // Use BrokerFrame.newBuilder() to construct.
  private BrokerFrame(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private BrokerFrame() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new BrokerFrame();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private BrokerFrame(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            org.doodle.broker.BrokerAddress.Builder subBuilder = null;
            if (frameCase_ == 1) {
              subBuilder = ((org.doodle.broker.BrokerAddress) frame_).toBuilder();
            }
            frame_ =
                input.readMessage(org.doodle.broker.BrokerAddress.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((org.doodle.broker.BrokerAddress) frame_);
              frame_ = subBuilder.buildPartial();
            }
            frameCase_ = 1;
            break;
          }
          case 18: {
            org.doodle.broker.BrokerRouteSetup.Builder subBuilder = null;
            if (frameCase_ == 2) {
              subBuilder = ((org.doodle.broker.BrokerRouteSetup) frame_).toBuilder();
            }
            frame_ =
                input.readMessage(org.doodle.broker.BrokerRouteSetup.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((org.doodle.broker.BrokerRouteSetup) frame_);
              frame_ = subBuilder.buildPartial();
            }
            frameCase_ = 2;
            break;
          }
          case 26: {
            org.doodle.broker.BrokerRouteJoin.Builder subBuilder = null;
            if (frameCase_ == 3) {
              subBuilder = ((org.doodle.broker.BrokerRouteJoin) frame_).toBuilder();
            }
            frame_ =
                input.readMessage(org.doodle.broker.BrokerRouteJoin.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((org.doodle.broker.BrokerRouteJoin) frame_);
              frame_ = subBuilder.buildPartial();
            }
            frameCase_ = 3;
            break;
          }
          case 34: {
            org.doodle.broker.BrokerInfo.Builder subBuilder = null;
            if (frameCase_ == 4) {
              subBuilder = ((org.doodle.broker.BrokerInfo) frame_).toBuilder();
            }
            frame_ =
                input.readMessage(org.doodle.broker.BrokerInfo.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((org.doodle.broker.BrokerInfo) frame_);
              frame_ = subBuilder.buildPartial();
            }
            frameCase_ = 4;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (com.google.protobuf.UninitializedMessageException e) {
      throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.doodle.broker.BrokerFrameProto.internal_static_doodle_broker_BrokerFrame_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.doodle.broker.BrokerFrameProto.internal_static_doodle_broker_BrokerFrame_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.doodle.broker.BrokerFrame.class, org.doodle.broker.BrokerFrame.Builder.class);
  }

  private int frameCase_ = 0;
  private java.lang.Object frame_;
  public enum FrameCase
      implements com.google.protobuf.Internal.EnumLite,
          com.google.protobuf.AbstractMessage.InternalOneOfEnum {
    ADDRESS(1),
    ROUTE_SETUP(2),
    ROUTE_JOIN(3),
    BROKER_INFO(4),
    FRAME_NOT_SET(0);
    private final int value;
    private FrameCase(int value) {
      this.value = value;
    }
    /**
     * @param value The number of the enum to look for.
     * @return The enum associated with the given number.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static FrameCase valueOf(int value) {
      return forNumber(value);
    }

    public static FrameCase forNumber(int value) {
      switch (value) {
        case 1: return ADDRESS;
        case 2: return ROUTE_SETUP;
        case 3: return ROUTE_JOIN;
        case 4: return BROKER_INFO;
        case 0: return FRAME_NOT_SET;
        default: return null;
      }
    }
    public int getNumber() {
      return this.value;
    }
  };

  public FrameCase
  getFrameCase() {
    return FrameCase.forNumber(
        frameCase_);
  }

  public static final int ADDRESS_FIELD_NUMBER = 1;
  /**
   * <code>.doodle.broker.BrokerAddress address = 1;</code>
   * @return Whether the address field is set.
   */
  @java.lang.Override
  public boolean hasAddress() {
    return frameCase_ == 1;
  }
  /**
   * <code>.doodle.broker.BrokerAddress address = 1;</code>
   * @return The address.
   */
  @java.lang.Override
  public org.doodle.broker.BrokerAddress getAddress() {
    if (frameCase_ == 1) {
       return (org.doodle.broker.BrokerAddress) frame_;
    }
    return org.doodle.broker.BrokerAddress.getDefaultInstance();
  }
  /**
   * <code>.doodle.broker.BrokerAddress address = 1;</code>
   */
  @java.lang.Override
  public org.doodle.broker.BrokerAddressOrBuilder getAddressOrBuilder() {
    if (frameCase_ == 1) {
       return (org.doodle.broker.BrokerAddress) frame_;
    }
    return org.doodle.broker.BrokerAddress.getDefaultInstance();
  }

  public static final int ROUTE_SETUP_FIELD_NUMBER = 2;
  /**
   * <code>.doodle.broker.BrokerRouteSetup route_setup = 2;</code>
   * @return Whether the routeSetup field is set.
   */
  @java.lang.Override
  public boolean hasRouteSetup() {
    return frameCase_ == 2;
  }
  /**
   * <code>.doodle.broker.BrokerRouteSetup route_setup = 2;</code>
   * @return The routeSetup.
   */
  @java.lang.Override
  public org.doodle.broker.BrokerRouteSetup getRouteSetup() {
    if (frameCase_ == 2) {
       return (org.doodle.broker.BrokerRouteSetup) frame_;
    }
    return org.doodle.broker.BrokerRouteSetup.getDefaultInstance();
  }
  /**
   * <code>.doodle.broker.BrokerRouteSetup route_setup = 2;</code>
   */
  @java.lang.Override
  public org.doodle.broker.BrokerRouteSetupOrBuilder getRouteSetupOrBuilder() {
    if (frameCase_ == 2) {
       return (org.doodle.broker.BrokerRouteSetup) frame_;
    }
    return org.doodle.broker.BrokerRouteSetup.getDefaultInstance();
  }

  public static final int ROUTE_JOIN_FIELD_NUMBER = 3;
  /**
   * <code>.doodle.broker.BrokerRouteJoin route_join = 3;</code>
   * @return Whether the routeJoin field is set.
   */
  @java.lang.Override
  public boolean hasRouteJoin() {
    return frameCase_ == 3;
  }
  /**
   * <code>.doodle.broker.BrokerRouteJoin route_join = 3;</code>
   * @return The routeJoin.
   */
  @java.lang.Override
  public org.doodle.broker.BrokerRouteJoin getRouteJoin() {
    if (frameCase_ == 3) {
       return (org.doodle.broker.BrokerRouteJoin) frame_;
    }
    return org.doodle.broker.BrokerRouteJoin.getDefaultInstance();
  }
  /**
   * <code>.doodle.broker.BrokerRouteJoin route_join = 3;</code>
   */
  @java.lang.Override
  public org.doodle.broker.BrokerRouteJoinOrBuilder getRouteJoinOrBuilder() {
    if (frameCase_ == 3) {
       return (org.doodle.broker.BrokerRouteJoin) frame_;
    }
    return org.doodle.broker.BrokerRouteJoin.getDefaultInstance();
  }

  public static final int BROKER_INFO_FIELD_NUMBER = 4;
  /**
   * <code>.doodle.broker.BrokerInfo broker_info = 4;</code>
   * @return Whether the brokerInfo field is set.
   */
  @java.lang.Override
  public boolean hasBrokerInfo() {
    return frameCase_ == 4;
  }
  /**
   * <code>.doodle.broker.BrokerInfo broker_info = 4;</code>
   * @return The brokerInfo.
   */
  @java.lang.Override
  public org.doodle.broker.BrokerInfo getBrokerInfo() {
    if (frameCase_ == 4) {
       return (org.doodle.broker.BrokerInfo) frame_;
    }
    return org.doodle.broker.BrokerInfo.getDefaultInstance();
  }
  /**
   * <code>.doodle.broker.BrokerInfo broker_info = 4;</code>
   */
  @java.lang.Override
  public org.doodle.broker.BrokerInfoOrBuilder getBrokerInfoOrBuilder() {
    if (frameCase_ == 4) {
       return (org.doodle.broker.BrokerInfo) frame_;
    }
    return org.doodle.broker.BrokerInfo.getDefaultInstance();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (frameCase_ == 1) {
      output.writeMessage(1, (org.doodle.broker.BrokerAddress) frame_);
    }
    if (frameCase_ == 2) {
      output.writeMessage(2, (org.doodle.broker.BrokerRouteSetup) frame_);
    }
    if (frameCase_ == 3) {
      output.writeMessage(3, (org.doodle.broker.BrokerRouteJoin) frame_);
    }
    if (frameCase_ == 4) {
      output.writeMessage(4, (org.doodle.broker.BrokerInfo) frame_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (frameCase_ == 1) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, (org.doodle.broker.BrokerAddress) frame_);
    }
    if (frameCase_ == 2) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, (org.doodle.broker.BrokerRouteSetup) frame_);
    }
    if (frameCase_ == 3) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, (org.doodle.broker.BrokerRouteJoin) frame_);
    }
    if (frameCase_ == 4) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, (org.doodle.broker.BrokerInfo) frame_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.doodle.broker.BrokerFrame)) {
      return super.equals(obj);
    }
    org.doodle.broker.BrokerFrame other = (org.doodle.broker.BrokerFrame) obj;

    if (!getFrameCase().equals(other.getFrameCase())) return false;
    switch (frameCase_) {
      case 1:
        if (!getAddress()
            .equals(other.getAddress())) return false;
        break;
      case 2:
        if (!getRouteSetup()
            .equals(other.getRouteSetup())) return false;
        break;
      case 3:
        if (!getRouteJoin()
            .equals(other.getRouteJoin())) return false;
        break;
      case 4:
        if (!getBrokerInfo()
            .equals(other.getBrokerInfo())) return false;
        break;
      case 0:
      default:
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    switch (frameCase_) {
      case 1:
        hash = (37 * hash) + ADDRESS_FIELD_NUMBER;
        hash = (53 * hash) + getAddress().hashCode();
        break;
      case 2:
        hash = (37 * hash) + ROUTE_SETUP_FIELD_NUMBER;
        hash = (53 * hash) + getRouteSetup().hashCode();
        break;
      case 3:
        hash = (37 * hash) + ROUTE_JOIN_FIELD_NUMBER;
        hash = (53 * hash) + getRouteJoin().hashCode();
        break;
      case 4:
        hash = (37 * hash) + BROKER_INFO_FIELD_NUMBER;
        hash = (53 * hash) + getBrokerInfo().hashCode();
        break;
      case 0:
      default:
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.doodle.broker.BrokerFrame parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.doodle.broker.BrokerFrame parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.doodle.broker.BrokerFrame parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.doodle.broker.BrokerFrame parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.doodle.broker.BrokerFrame parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.doodle.broker.BrokerFrame parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.doodle.broker.BrokerFrame parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.doodle.broker.BrokerFrame parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.doodle.broker.BrokerFrame parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static org.doodle.broker.BrokerFrame parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.doodle.broker.BrokerFrame parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.doodle.broker.BrokerFrame parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.doodle.broker.BrokerFrame prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code doodle.broker.BrokerFrame}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:doodle.broker.BrokerFrame)
      org.doodle.broker.BrokerFrameOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.doodle.broker.BrokerFrameProto.internal_static_doodle_broker_BrokerFrame_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.doodle.broker.BrokerFrameProto.internal_static_doodle_broker_BrokerFrame_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.doodle.broker.BrokerFrame.class, org.doodle.broker.BrokerFrame.Builder.class);
    }

    // Construct using org.doodle.broker.BrokerFrame.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      frameCase_ = 0;
      frame_ = null;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.doodle.broker.BrokerFrameProto.internal_static_doodle_broker_BrokerFrame_descriptor;
    }

    @java.lang.Override
    public org.doodle.broker.BrokerFrame getDefaultInstanceForType() {
      return org.doodle.broker.BrokerFrame.getDefaultInstance();
    }

    @java.lang.Override
    public org.doodle.broker.BrokerFrame build() {
      org.doodle.broker.BrokerFrame result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public org.doodle.broker.BrokerFrame buildPartial() {
      org.doodle.broker.BrokerFrame result = new org.doodle.broker.BrokerFrame(this);
      if (frameCase_ == 1) {
        if (addressBuilder_ == null) {
          result.frame_ = frame_;
        } else {
          result.frame_ = addressBuilder_.build();
        }
      }
      if (frameCase_ == 2) {
        if (routeSetupBuilder_ == null) {
          result.frame_ = frame_;
        } else {
          result.frame_ = routeSetupBuilder_.build();
        }
      }
      if (frameCase_ == 3) {
        if (routeJoinBuilder_ == null) {
          result.frame_ = frame_;
        } else {
          result.frame_ = routeJoinBuilder_.build();
        }
      }
      if (frameCase_ == 4) {
        if (brokerInfoBuilder_ == null) {
          result.frame_ = frame_;
        } else {
          result.frame_ = brokerInfoBuilder_.build();
        }
      }
      result.frameCase_ = frameCase_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.doodle.broker.BrokerFrame) {
        return mergeFrom((org.doodle.broker.BrokerFrame)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.doodle.broker.BrokerFrame other) {
      if (other == org.doodle.broker.BrokerFrame.getDefaultInstance()) return this;
      switch (other.getFrameCase()) {
        case ADDRESS: {
          mergeAddress(other.getAddress());
          break;
        }
        case ROUTE_SETUP: {
          mergeRouteSetup(other.getRouteSetup());
          break;
        }
        case ROUTE_JOIN: {
          mergeRouteJoin(other.getRouteJoin());
          break;
        }
        case BROKER_INFO: {
          mergeBrokerInfo(other.getBrokerInfo());
          break;
        }
        case FRAME_NOT_SET: {
          break;
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      org.doodle.broker.BrokerFrame parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (org.doodle.broker.BrokerFrame) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int frameCase_ = 0;
    private java.lang.Object frame_;
    public FrameCase
        getFrameCase() {
      return FrameCase.forNumber(
          frameCase_);
    }

    public Builder clearFrame() {
      frameCase_ = 0;
      frame_ = null;
      onChanged();
      return this;
    }


    private com.google.protobuf.SingleFieldBuilderV3<
        org.doodle.broker.BrokerAddress, org.doodle.broker.BrokerAddress.Builder, org.doodle.broker.BrokerAddressOrBuilder> addressBuilder_;
    /**
     * <code>.doodle.broker.BrokerAddress address = 1;</code>
     * @return Whether the address field is set.
     */
    @java.lang.Override
    public boolean hasAddress() {
      return frameCase_ == 1;
    }
    /**
     * <code>.doodle.broker.BrokerAddress address = 1;</code>
     * @return The address.
     */
    @java.lang.Override
    public org.doodle.broker.BrokerAddress getAddress() {
      if (addressBuilder_ == null) {
        if (frameCase_ == 1) {
          return (org.doodle.broker.BrokerAddress) frame_;
        }
        return org.doodle.broker.BrokerAddress.getDefaultInstance();
      } else {
        if (frameCase_ == 1) {
          return addressBuilder_.getMessage();
        }
        return org.doodle.broker.BrokerAddress.getDefaultInstance();
      }
    }
    /**
     * <code>.doodle.broker.BrokerAddress address = 1;</code>
     */
    public Builder setAddress(org.doodle.broker.BrokerAddress value) {
      if (addressBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        frame_ = value;
        onChanged();
      } else {
        addressBuilder_.setMessage(value);
      }
      frameCase_ = 1;
      return this;
    }
    /**
     * <code>.doodle.broker.BrokerAddress address = 1;</code>
     */
    public Builder setAddress(
        org.doodle.broker.BrokerAddress.Builder builderForValue) {
      if (addressBuilder_ == null) {
        frame_ = builderForValue.build();
        onChanged();
      } else {
        addressBuilder_.setMessage(builderForValue.build());
      }
      frameCase_ = 1;
      return this;
    }
    /**
     * <code>.doodle.broker.BrokerAddress address = 1;</code>
     */
    public Builder mergeAddress(org.doodle.broker.BrokerAddress value) {
      if (addressBuilder_ == null) {
        if (frameCase_ == 1 &&
            frame_ != org.doodle.broker.BrokerAddress.getDefaultInstance()) {
          frame_ = org.doodle.broker.BrokerAddress.newBuilder((org.doodle.broker.BrokerAddress) frame_)
              .mergeFrom(value).buildPartial();
        } else {
          frame_ = value;
        }
        onChanged();
      } else {
        if (frameCase_ == 1) {
          addressBuilder_.mergeFrom(value);
        } else {
          addressBuilder_.setMessage(value);
        }
      }
      frameCase_ = 1;
      return this;
    }
    /**
     * <code>.doodle.broker.BrokerAddress address = 1;</code>
     */
    public Builder clearAddress() {
      if (addressBuilder_ == null) {
        if (frameCase_ == 1) {
          frameCase_ = 0;
          frame_ = null;
          onChanged();
        }
      } else {
        if (frameCase_ == 1) {
          frameCase_ = 0;
          frame_ = null;
        }
        addressBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.doodle.broker.BrokerAddress address = 1;</code>
     */
    public org.doodle.broker.BrokerAddress.Builder getAddressBuilder() {
      return getAddressFieldBuilder().getBuilder();
    }
    /**
     * <code>.doodle.broker.BrokerAddress address = 1;</code>
     */
    @java.lang.Override
    public org.doodle.broker.BrokerAddressOrBuilder getAddressOrBuilder() {
      if ((frameCase_ == 1) && (addressBuilder_ != null)) {
        return addressBuilder_.getMessageOrBuilder();
      } else {
        if (frameCase_ == 1) {
          return (org.doodle.broker.BrokerAddress) frame_;
        }
        return org.doodle.broker.BrokerAddress.getDefaultInstance();
      }
    }
    /**
     * <code>.doodle.broker.BrokerAddress address = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        org.doodle.broker.BrokerAddress, org.doodle.broker.BrokerAddress.Builder, org.doodle.broker.BrokerAddressOrBuilder> 
        getAddressFieldBuilder() {
      if (addressBuilder_ == null) {
        if (!(frameCase_ == 1)) {
          frame_ = org.doodle.broker.BrokerAddress.getDefaultInstance();
        }
        addressBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            org.doodle.broker.BrokerAddress, org.doodle.broker.BrokerAddress.Builder, org.doodle.broker.BrokerAddressOrBuilder>(
                (org.doodle.broker.BrokerAddress) frame_,
                getParentForChildren(),
                isClean());
        frame_ = null;
      }
      frameCase_ = 1;
      onChanged();;
      return addressBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        org.doodle.broker.BrokerRouteSetup, org.doodle.broker.BrokerRouteSetup.Builder, org.doodle.broker.BrokerRouteSetupOrBuilder> routeSetupBuilder_;
    /**
     * <code>.doodle.broker.BrokerRouteSetup route_setup = 2;</code>
     * @return Whether the routeSetup field is set.
     */
    @java.lang.Override
    public boolean hasRouteSetup() {
      return frameCase_ == 2;
    }
    /**
     * <code>.doodle.broker.BrokerRouteSetup route_setup = 2;</code>
     * @return The routeSetup.
     */
    @java.lang.Override
    public org.doodle.broker.BrokerRouteSetup getRouteSetup() {
      if (routeSetupBuilder_ == null) {
        if (frameCase_ == 2) {
          return (org.doodle.broker.BrokerRouteSetup) frame_;
        }
        return org.doodle.broker.BrokerRouteSetup.getDefaultInstance();
      } else {
        if (frameCase_ == 2) {
          return routeSetupBuilder_.getMessage();
        }
        return org.doodle.broker.BrokerRouteSetup.getDefaultInstance();
      }
    }
    /**
     * <code>.doodle.broker.BrokerRouteSetup route_setup = 2;</code>
     */
    public Builder setRouteSetup(org.doodle.broker.BrokerRouteSetup value) {
      if (routeSetupBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        frame_ = value;
        onChanged();
      } else {
        routeSetupBuilder_.setMessage(value);
      }
      frameCase_ = 2;
      return this;
    }
    /**
     * <code>.doodle.broker.BrokerRouteSetup route_setup = 2;</code>
     */
    public Builder setRouteSetup(
        org.doodle.broker.BrokerRouteSetup.Builder builderForValue) {
      if (routeSetupBuilder_ == null) {
        frame_ = builderForValue.build();
        onChanged();
      } else {
        routeSetupBuilder_.setMessage(builderForValue.build());
      }
      frameCase_ = 2;
      return this;
    }
    /**
     * <code>.doodle.broker.BrokerRouteSetup route_setup = 2;</code>
     */
    public Builder mergeRouteSetup(org.doodle.broker.BrokerRouteSetup value) {
      if (routeSetupBuilder_ == null) {
        if (frameCase_ == 2 &&
            frame_ != org.doodle.broker.BrokerRouteSetup.getDefaultInstance()) {
          frame_ = org.doodle.broker.BrokerRouteSetup.newBuilder((org.doodle.broker.BrokerRouteSetup) frame_)
              .mergeFrom(value).buildPartial();
        } else {
          frame_ = value;
        }
        onChanged();
      } else {
        if (frameCase_ == 2) {
          routeSetupBuilder_.mergeFrom(value);
        } else {
          routeSetupBuilder_.setMessage(value);
        }
      }
      frameCase_ = 2;
      return this;
    }
    /**
     * <code>.doodle.broker.BrokerRouteSetup route_setup = 2;</code>
     */
    public Builder clearRouteSetup() {
      if (routeSetupBuilder_ == null) {
        if (frameCase_ == 2) {
          frameCase_ = 0;
          frame_ = null;
          onChanged();
        }
      } else {
        if (frameCase_ == 2) {
          frameCase_ = 0;
          frame_ = null;
        }
        routeSetupBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.doodle.broker.BrokerRouteSetup route_setup = 2;</code>
     */
    public org.doodle.broker.BrokerRouteSetup.Builder getRouteSetupBuilder() {
      return getRouteSetupFieldBuilder().getBuilder();
    }
    /**
     * <code>.doodle.broker.BrokerRouteSetup route_setup = 2;</code>
     */
    @java.lang.Override
    public org.doodle.broker.BrokerRouteSetupOrBuilder getRouteSetupOrBuilder() {
      if ((frameCase_ == 2) && (routeSetupBuilder_ != null)) {
        return routeSetupBuilder_.getMessageOrBuilder();
      } else {
        if (frameCase_ == 2) {
          return (org.doodle.broker.BrokerRouteSetup) frame_;
        }
        return org.doodle.broker.BrokerRouteSetup.getDefaultInstance();
      }
    }
    /**
     * <code>.doodle.broker.BrokerRouteSetup route_setup = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        org.doodle.broker.BrokerRouteSetup, org.doodle.broker.BrokerRouteSetup.Builder, org.doodle.broker.BrokerRouteSetupOrBuilder> 
        getRouteSetupFieldBuilder() {
      if (routeSetupBuilder_ == null) {
        if (!(frameCase_ == 2)) {
          frame_ = org.doodle.broker.BrokerRouteSetup.getDefaultInstance();
        }
        routeSetupBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            org.doodle.broker.BrokerRouteSetup, org.doodle.broker.BrokerRouteSetup.Builder, org.doodle.broker.BrokerRouteSetupOrBuilder>(
                (org.doodle.broker.BrokerRouteSetup) frame_,
                getParentForChildren(),
                isClean());
        frame_ = null;
      }
      frameCase_ = 2;
      onChanged();;
      return routeSetupBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        org.doodle.broker.BrokerRouteJoin, org.doodle.broker.BrokerRouteJoin.Builder, org.doodle.broker.BrokerRouteJoinOrBuilder> routeJoinBuilder_;
    /**
     * <code>.doodle.broker.BrokerRouteJoin route_join = 3;</code>
     * @return Whether the routeJoin field is set.
     */
    @java.lang.Override
    public boolean hasRouteJoin() {
      return frameCase_ == 3;
    }
    /**
     * <code>.doodle.broker.BrokerRouteJoin route_join = 3;</code>
     * @return The routeJoin.
     */
    @java.lang.Override
    public org.doodle.broker.BrokerRouteJoin getRouteJoin() {
      if (routeJoinBuilder_ == null) {
        if (frameCase_ == 3) {
          return (org.doodle.broker.BrokerRouteJoin) frame_;
        }
        return org.doodle.broker.BrokerRouteJoin.getDefaultInstance();
      } else {
        if (frameCase_ == 3) {
          return routeJoinBuilder_.getMessage();
        }
        return org.doodle.broker.BrokerRouteJoin.getDefaultInstance();
      }
    }
    /**
     * <code>.doodle.broker.BrokerRouteJoin route_join = 3;</code>
     */
    public Builder setRouteJoin(org.doodle.broker.BrokerRouteJoin value) {
      if (routeJoinBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        frame_ = value;
        onChanged();
      } else {
        routeJoinBuilder_.setMessage(value);
      }
      frameCase_ = 3;
      return this;
    }
    /**
     * <code>.doodle.broker.BrokerRouteJoin route_join = 3;</code>
     */
    public Builder setRouteJoin(
        org.doodle.broker.BrokerRouteJoin.Builder builderForValue) {
      if (routeJoinBuilder_ == null) {
        frame_ = builderForValue.build();
        onChanged();
      } else {
        routeJoinBuilder_.setMessage(builderForValue.build());
      }
      frameCase_ = 3;
      return this;
    }
    /**
     * <code>.doodle.broker.BrokerRouteJoin route_join = 3;</code>
     */
    public Builder mergeRouteJoin(org.doodle.broker.BrokerRouteJoin value) {
      if (routeJoinBuilder_ == null) {
        if (frameCase_ == 3 &&
            frame_ != org.doodle.broker.BrokerRouteJoin.getDefaultInstance()) {
          frame_ = org.doodle.broker.BrokerRouteJoin.newBuilder((org.doodle.broker.BrokerRouteJoin) frame_)
              .mergeFrom(value).buildPartial();
        } else {
          frame_ = value;
        }
        onChanged();
      } else {
        if (frameCase_ == 3) {
          routeJoinBuilder_.mergeFrom(value);
        } else {
          routeJoinBuilder_.setMessage(value);
        }
      }
      frameCase_ = 3;
      return this;
    }
    /**
     * <code>.doodle.broker.BrokerRouteJoin route_join = 3;</code>
     */
    public Builder clearRouteJoin() {
      if (routeJoinBuilder_ == null) {
        if (frameCase_ == 3) {
          frameCase_ = 0;
          frame_ = null;
          onChanged();
        }
      } else {
        if (frameCase_ == 3) {
          frameCase_ = 0;
          frame_ = null;
        }
        routeJoinBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.doodle.broker.BrokerRouteJoin route_join = 3;</code>
     */
    public org.doodle.broker.BrokerRouteJoin.Builder getRouteJoinBuilder() {
      return getRouteJoinFieldBuilder().getBuilder();
    }
    /**
     * <code>.doodle.broker.BrokerRouteJoin route_join = 3;</code>
     */
    @java.lang.Override
    public org.doodle.broker.BrokerRouteJoinOrBuilder getRouteJoinOrBuilder() {
      if ((frameCase_ == 3) && (routeJoinBuilder_ != null)) {
        return routeJoinBuilder_.getMessageOrBuilder();
      } else {
        if (frameCase_ == 3) {
          return (org.doodle.broker.BrokerRouteJoin) frame_;
        }
        return org.doodle.broker.BrokerRouteJoin.getDefaultInstance();
      }
    }
    /**
     * <code>.doodle.broker.BrokerRouteJoin route_join = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        org.doodle.broker.BrokerRouteJoin, org.doodle.broker.BrokerRouteJoin.Builder, org.doodle.broker.BrokerRouteJoinOrBuilder> 
        getRouteJoinFieldBuilder() {
      if (routeJoinBuilder_ == null) {
        if (!(frameCase_ == 3)) {
          frame_ = org.doodle.broker.BrokerRouteJoin.getDefaultInstance();
        }
        routeJoinBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            org.doodle.broker.BrokerRouteJoin, org.doodle.broker.BrokerRouteJoin.Builder, org.doodle.broker.BrokerRouteJoinOrBuilder>(
                (org.doodle.broker.BrokerRouteJoin) frame_,
                getParentForChildren(),
                isClean());
        frame_ = null;
      }
      frameCase_ = 3;
      onChanged();;
      return routeJoinBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        org.doodle.broker.BrokerInfo, org.doodle.broker.BrokerInfo.Builder, org.doodle.broker.BrokerInfoOrBuilder> brokerInfoBuilder_;
    /**
     * <code>.doodle.broker.BrokerInfo broker_info = 4;</code>
     * @return Whether the brokerInfo field is set.
     */
    @java.lang.Override
    public boolean hasBrokerInfo() {
      return frameCase_ == 4;
    }
    /**
     * <code>.doodle.broker.BrokerInfo broker_info = 4;</code>
     * @return The brokerInfo.
     */
    @java.lang.Override
    public org.doodle.broker.BrokerInfo getBrokerInfo() {
      if (brokerInfoBuilder_ == null) {
        if (frameCase_ == 4) {
          return (org.doodle.broker.BrokerInfo) frame_;
        }
        return org.doodle.broker.BrokerInfo.getDefaultInstance();
      } else {
        if (frameCase_ == 4) {
          return brokerInfoBuilder_.getMessage();
        }
        return org.doodle.broker.BrokerInfo.getDefaultInstance();
      }
    }
    /**
     * <code>.doodle.broker.BrokerInfo broker_info = 4;</code>
     */
    public Builder setBrokerInfo(org.doodle.broker.BrokerInfo value) {
      if (brokerInfoBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        frame_ = value;
        onChanged();
      } else {
        brokerInfoBuilder_.setMessage(value);
      }
      frameCase_ = 4;
      return this;
    }
    /**
     * <code>.doodle.broker.BrokerInfo broker_info = 4;</code>
     */
    public Builder setBrokerInfo(
        org.doodle.broker.BrokerInfo.Builder builderForValue) {
      if (brokerInfoBuilder_ == null) {
        frame_ = builderForValue.build();
        onChanged();
      } else {
        brokerInfoBuilder_.setMessage(builderForValue.build());
      }
      frameCase_ = 4;
      return this;
    }
    /**
     * <code>.doodle.broker.BrokerInfo broker_info = 4;</code>
     */
    public Builder mergeBrokerInfo(org.doodle.broker.BrokerInfo value) {
      if (brokerInfoBuilder_ == null) {
        if (frameCase_ == 4 &&
            frame_ != org.doodle.broker.BrokerInfo.getDefaultInstance()) {
          frame_ = org.doodle.broker.BrokerInfo.newBuilder((org.doodle.broker.BrokerInfo) frame_)
              .mergeFrom(value).buildPartial();
        } else {
          frame_ = value;
        }
        onChanged();
      } else {
        if (frameCase_ == 4) {
          brokerInfoBuilder_.mergeFrom(value);
        } else {
          brokerInfoBuilder_.setMessage(value);
        }
      }
      frameCase_ = 4;
      return this;
    }
    /**
     * <code>.doodle.broker.BrokerInfo broker_info = 4;</code>
     */
    public Builder clearBrokerInfo() {
      if (brokerInfoBuilder_ == null) {
        if (frameCase_ == 4) {
          frameCase_ = 0;
          frame_ = null;
          onChanged();
        }
      } else {
        if (frameCase_ == 4) {
          frameCase_ = 0;
          frame_ = null;
        }
        brokerInfoBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.doodle.broker.BrokerInfo broker_info = 4;</code>
     */
    public org.doodle.broker.BrokerInfo.Builder getBrokerInfoBuilder() {
      return getBrokerInfoFieldBuilder().getBuilder();
    }
    /**
     * <code>.doodle.broker.BrokerInfo broker_info = 4;</code>
     */
    @java.lang.Override
    public org.doodle.broker.BrokerInfoOrBuilder getBrokerInfoOrBuilder() {
      if ((frameCase_ == 4) && (brokerInfoBuilder_ != null)) {
        return brokerInfoBuilder_.getMessageOrBuilder();
      } else {
        if (frameCase_ == 4) {
          return (org.doodle.broker.BrokerInfo) frame_;
        }
        return org.doodle.broker.BrokerInfo.getDefaultInstance();
      }
    }
    /**
     * <code>.doodle.broker.BrokerInfo broker_info = 4;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        org.doodle.broker.BrokerInfo, org.doodle.broker.BrokerInfo.Builder, org.doodle.broker.BrokerInfoOrBuilder> 
        getBrokerInfoFieldBuilder() {
      if (brokerInfoBuilder_ == null) {
        if (!(frameCase_ == 4)) {
          frame_ = org.doodle.broker.BrokerInfo.getDefaultInstance();
        }
        brokerInfoBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            org.doodle.broker.BrokerInfo, org.doodle.broker.BrokerInfo.Builder, org.doodle.broker.BrokerInfoOrBuilder>(
                (org.doodle.broker.BrokerInfo) frame_,
                getParentForChildren(),
                isClean());
        frame_ = null;
      }
      frameCase_ = 4;
      onChanged();;
      return brokerInfoBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:doodle.broker.BrokerFrame)
  }

  // @@protoc_insertion_point(class_scope:doodle.broker.BrokerFrame)
  private static final org.doodle.broker.BrokerFrame DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.doodle.broker.BrokerFrame();
  }

  public static org.doodle.broker.BrokerFrame getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<BrokerFrame>
      PARSER = new com.google.protobuf.AbstractParser<BrokerFrame>() {
    @java.lang.Override
    public BrokerFrame parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new BrokerFrame(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<BrokerFrame> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<BrokerFrame> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public org.doodle.broker.BrokerFrame getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

