// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: broker/route_id.proto

package org.doodle.broker;

public final class BrokerRouteIdProto {
  private BrokerRouteIdProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_doodle_broker_BrokerRouteId_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_doodle_broker_BrokerRouteId_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\025broker/route_id.proto\022\rdoodle.broker\")" +
      "\n\rBrokerRouteId\022\013\n\003msb\030\001 \001(\003\022\013\n\003lsb\030\002 \001(" +
      "\003B)\n\021org.doodle.brokerB\022BrokerRouteIdPro" +
      "toP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_doodle_broker_BrokerRouteId_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_doodle_broker_BrokerRouteId_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_doodle_broker_BrokerRouteId_descriptor,
        new java.lang.String[] { "Msb", "Lsb", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
