// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: broker/route_join.proto

package org.doodle.broker;

public final class BrokerRouteJoinProto {
  private BrokerRouteJoinProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_doodle_broker_BrokerRouteJoin_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_doodle_broker_BrokerRouteJoin_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\027broker/route_join.proto\022\rdoodle.broker" +
      "\"\021\n\017BrokerRouteJoinB+\n\021org.doodle.broker" +
      "B\024BrokerRouteJoinProtoP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_doodle_broker_BrokerRouteJoin_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_doodle_broker_BrokerRouteJoin_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_doodle_broker_BrokerRouteJoin_descriptor,
        new java.lang.String[] { });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
