// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: broker/route_join.proto

package org.doodle.broker;

public interface BrokerRouteJoinOrBuilder extends
    // @@protoc_insertion_point(interface_extends:doodle.broker.BrokerRouteJoin)
    com.google.protobuf.MessageOrBuilder {
}
